language: python

sudo: false

addons:
  apt:
    packages:
    - rubberband-cli
    - ffmpeg
    - libsndfile1
    - sox

cache:
  directories:
  - $HOME/env

notifications:
  email: false

python:
    - "2.7"
    - "3.4"
    - "3.5"

before_install:
    - bash .travis_dependencies.sh
    - export PATH="$HOME/env/miniconda$TRAVIS_PYTHON_VERSION/bin:$PATH";
    - hash -r
    - source activate test-environment

install:
    # install your own package into the environment
    - pip install -e .

script:
    - nosetests -v -w tests/ --with-coverage --cover-erase --cover-package=muda

after_success:
    - coveralls
    - pip uninstall -y muda

after_failure:
    - pip uninstall -y muda
